In [15]:

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Setting the working directory

In [10]:
import os
os.getcwd()
os.chdir('D:\\Unlearn_Learn\\Deep_Learning_A_Z\\Volume 1 - Supervised Deep Learning\\
Part 1 - Artificial Neural Networks (ANN)\\Section 4 - Building an ANN\\Artificial_Neural_Networks\\Artificial_Neural_Networks')

In [11]:
### Checking the content of the directory
os.listdir()

['ann.py',
 'ann_homework_solution.py',
 'categorical_data.py',
 'Churn_Modelling.csv',
 'classification_template.py',
 'evaluating_improving_tuning.py',
 'Installations_Instructions.pdf']

### Importing the libraries

In [ ]:
%%time
import pandas as pd 
import numpy as npp
import matplotlib.pyplot as plt
import seasborn as sns
import tensorflow as tf
%matplotlib inline

### Getting the Data 

In [17]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [24]:
data.columns
print(len(data.columns))

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

14


### Converting the categorical variables


In [46]:
data_dumm1 = pd.get_dummies(data['Geography'],drop_first=True,prefix='dumm')
data_dumm2 = pd.get_dummies(data.Gender,drop_first=True,prefix = 'dumm')
data_no_cat_var = data.drop(['Geography','Gender'],axis=1)

data_fin = pd.concat([data_no_cat_var,data_dumm1,data_dumm2],axis=1)
data_fin.head()

RowNumber  CustomerId   Surname  CreditScore  Age  Tenure    Balance  \
0          1    15634602  Hargrave          619   42       2       0.00   
1          2    15647311      Hill          608   41       1   83807.86   
2          3    15619304      Onio          502   42       8  159660.80   
3          4    15701354      Boni          699   39       1       0.00   
4          5    15737888  Mitchell          850   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0              1          1               1        101348.88       1   
1              1          0               1        112542.58       0   
2              3          1               0        113931.57       1   
3              2          0               0         93826.63       0   
4              1          1               1         79084.10       0   

   dumm_Germany  dumm_Spain  dumm_Male  
0             0           0          0  
1             0           1          0  
2             0           0          0  
3             0           0          0  
4             0           1          0

In [61]:
### Splitting the data into Target and Predictors
X = data_fin.drop(['RowNumber', 'CustomerId', 'Surname','Exited'],axis=1).values
y = data_fin[['Exited']].values

In [62]:
### Splitting into training and Test Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [65]:
### Standardisation
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Building the ANN

In [67]:
### Importing the libraries
import keras 

Using TensorFlow backend.


In [68]:
### Getting the modules from the Keras
### Sequential Module- to initialize the neural network
### Dense module - to build the layers of the ANN
from keras.models import Sequential
from keras.layers import Dense

In [69]:
### Initializing the ANN.. Defining the sequence of layers
classifier = Sequential()

In [70]:
### Adding input layer and the first hidden layer
### Thumb rule to find the number of nodes in the hidden layer = Average(no.of input nodes, output node)
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11)) ### Rectifier func - relu

In [71]:
### Adding the second hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu')) 

In [72]:
### Adding the output layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid')) ### Sigmoid Func - Sigmoid for binary output

### If the output has more than two levesl then we will be using activation ='softmax'



In [73]:
### Compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy']) 

### optimizer algo used to find the optimal set of weights for the neural network--stocashtic gradient decent
### Loss function here will be LOGARITHMIC LOSS.. If the output is binary in nature then LOGARITHMIC LOSS is binary_crossentropy 
### If the output  is of more than 2 levels then LOGARITMIC LOSS is categorical_crossentropy

In [74]:
### Fitting the ANN to the Training set
classifier.fit(X_train,y_train,batch_size=10, epochs=100)
### Batch size is the number of the observations after which weights gets updated
### Epoch is the number of time the entire data set set is passed through the ANN

Epoch 1/100
8000/8000 [==============================] - 3s - loss: 0.4847 - acc: 0.7959     
Epoch 2/100
8000/8000 [==============================] - 1s - loss: 0.4214 - acc: 0.7960     
Epoch 3/100
8000/8000 [==============================] - 1s - loss: 0.4100 - acc: 0.8052     - ETA: 1s - los
Epoch 4/100
8000/8000 [==============================] - 1s - loss: 0.4012 - acc: 0.8280     
Epoch 5/100
8000/8000 [==============================] - 1s - loss: 0.3916 - acc: 0.8305     
Epoch 6/100
8000/8000 [==============================] - 1s - loss: 0.3853 - acc: 0.8309     
Epoch 7/100
8000/8000 [==============================] - 1s - loss: 0.3796 - acc: 0.8412     
Epoch 8/100
8000/8000 [==============================] - 1s - loss: 0.3753 - acc: 0.8442     
Epoch 9/100
8000/8000 [==============================] - 1s - loss: 0.3711 - acc: 0.8482     
Epoch 10/100
8000/8000 [==============================] - 1s - loss: 0.3692 - acc: 0.8481     
Epoch 11/100
8000/8000 [====================

8000/8000 [==============================] - 1s - loss: 0.3380 - acc: 0.8631     
Epoch 87/100
8000/8000 [==============================] - 1s - loss: 0.3365 - acc: 0.8624     
Epoch 88/100
8000/8000 [==============================] - 1s - loss: 0.3372 - acc: 0.8617     
Epoch 89/100
8000/8000 [==============================] - 1s - loss: 0.3382 - acc: 0.8605     
Epoch 90/100
8000/8000 [==============================] - 1s - loss: 0.3376 - acc: 0.8611     
Epoch 91/100
8000/8000 [==============================] - 1s - loss: 0.3372 - acc: 0.8621     - ETA: 0s - loss: 0.3394 - acc
Epoch 92/100
8000/8000 [==============================] - 1s - loss: 0.3377 - acc: 0.8619     
Epoch 93/100
8000/8000 [==============================] - 1s - loss: 0.3368 - acc: 0.8630     
Epoch 94/100
8000/8000 [==============================] - 1s - loss: 0.3359 - acc: 0.8625     
Epoch 95/100
8000/8000 [==============================] - 1s - loss: 0.3384 - acc: 0.8616     
Epoch 96/100
8000/8000 [=========

In [78]:
### Predicting the test data
y_pred = classifier.predict(X_test) ## output is the probability
#y_pred

### Converting the probab into 1 and 0 by setting the threshold
y_pred = (y_pred > 0.5)
y_pred


array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

array([[0],
       [1],
       [0],
       ..., 
       [0],
       [0],
       [0]], dtype=int64)

In [79]:
### Evaluation Metric - confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[1508,   87],
       [ 197,  208]], dtype=int64)

In [80]:
Acc = (1508+208)/(1508+87+197+208)
Acc

0.858